### ISSUE TITLE
Assignment 3 - Iris database mention

### ISSUE THREAD

**Issue by G0rocks** [T809DATA/T809DATA_2024#6]
Readme says:
"So far we have tried to classify flowers from the Iris dataset. Classification tasks assume that we have a set of features and a set of class labels that we would like our models to learn to predict."

.... This is the first time in this version of the class that we've seen or talked about the iris dataset so the readme should be modified.

**Comment by thdg** [comment]
We did use the Iris dataset in the Independent section of Assignment 2. If you skipped that you have not seen this data before.
