### ISSUE TITLE
Assignment 3 - Missing square of standard deviation

### ISSUE THREAD

**Issue by G0rocks** [T809DATA/T809DATA_2024#8]
In assignment 3, section 1, it says:

"We control the shift of the basis function using the mean vector μ k , but we force all covariance matrices to be identical and diagonal Σ k = σ I for all k so σ is t"

But a covariance matrix has the variance on the diagonal and the variance is the standard deviation squared so it should be

"We control the shift of the basis function using the mean vector μ k , but we force all covariance matrices to be identical and diagonal Σ k = σ^2 I for all k so σ is t"

Please fix, thank you.

**Comment by thdg** [comment]
This would be more in line with standard usage of sigma in this context, i.e sigma = standard deviation. It means I also changed the input variable name to var instead of sigma, since sigma was used to represent the variance.

**Comment by G0rocks** [comment]
Thanks for updating this, it's clearer now.
But 1 more thing is now the comment in the template.py file says
"var: All normal distributions are isotropic with sigma^2*I covariance
    matrices (where I is the MxM identity matrix)"
In the function mvn_basis
But it leaves you wondering if the var is supposed to be the variance or the covariance matrix. I guess I'll see which one it's talking about when I turn it into gradescope but it could be clearer.
I thought it was ambiguous since the variable name is var indicating it's the variance but the comment that is supposed to clarify what variable this is talks about the covariance matrix, indicating that the variable is the covariance matrix?

Would be great if you could update this as well, thanks :)

Just noticed that in the readme this is clarified but leave this comment here anyway so the issue reopens and you can make this template.py even more explicit.
